export const FETCH_PLAYER_DATA_START = 'FETCH_PLAYER_DATA_START';
export const FETCH_PLAYER_DATA_SUCCESS = 'FETCH_PLAYER_DATA_SUCCESS';
export const FETCH_PLAYER_DATA_FAILURE = 'FETCH_PLAYER_DATA_FAILURE';
